///
/// @Generated by Mockolo
///



import Foundation


public class ProjectDaoMock: ProjectDao {
    public init() { }


    public private(set) var addProjectCallCount = 0
    public var addProjectHandler: ((Project) -> ())?
    public func addProject(_ project: Project)  {
        addProjectCallCount += 1
        if let addProjectHandler = addProjectHandler {
            addProjectHandler(project)
        }
        
    }
}

